spring:
  profiles:
    active: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://noriter-sonar.cxb87rqx7cpa.ap-northeast-2.rds.amazonaws.com:3306/noriter
    username: philsohanse
    password: ${DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    database: mysql

  config:
    import: classpath:oauth.yml

logging.level:
  org.hibernate.SQL: debug
