spring:
  profiles:
    active: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/noriter_test?useSSL=false
    username: 1sephil
    password: Password1!

  jpa:
    properties:
      hibernate:
        format_sql: true
    database: mysql

  config:
    import: classpath:oauth.yml

logging.level:
  org.hibernate.SQL: debug
