spring:
  profiles:
    active: ${NORITER_PROFILE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    database: mysql

  config:
    import: classpath:oauth.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"

  server:
    tomcat:
      mbeanregistry:
        enabled: true

logging.level:
  org.hibernate.SQL: debug
