spring:
  profiles:
    active: ${NORITER_PROFILE}

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
#        ddl-auto: create
        format_sql: true

  config:
    import: classpath:oauth.yml

logging.level:
  org.hibernate.SQL: debug
